name: Secrets

on:
  pull_request:
    branches: ["main"]

  workflow_dispatch:

env:
  API_CSPROJ_PATH: "./src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj"

jobs:
  build:
    name: "Secrets Demo"
    runs-on: ubuntu-latest

    steps:
      - name: echo enviro variables
        run: echo "my fake secret ${{ secrets.SECRET_API_KEY }}"        